name: Build and Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_GENERATE_ASPNET_CERTIFICATE: 0

jobs:
  build-and-test:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      VERSION_SUFFIX: ci
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Build
        shell: pwsh
        run: ./build.ps1 -VersionSuffix "$env:VERSION_SUFFIX"

  publish:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write  # enable GitHub OIDC token issuance for this job
    env:
      VERSION_SUFFIX: ""
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Build
        shell: pwsh
        run: ./build.ps1 -VersionSuffix "$env:VERSION_SUFFIX"

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC -> temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      # Push the packages
      - name: NuGet push
        run: dotnet nuget push *.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
